package objects;

public enum Ereignis {
	TYPE_LOGIN(0),
	TYPE_REGISTER(1),
	TYPE_UPLOAD(2),
	TYPE_CREATE_BEITRAG(3),
	TYPE_EDIT_BEITRAG(4),
	TYPE_CREATE_PROJEKT(5),
	TYPE_JOIN_PROJEKT(6),
	TYPE_QUIT_PROJEKT(7),
	TYPE_DELETE_PROJEKT(8),
	TYPE_JOIN_KLASSE(9),
	TYPE_QUIT_KLASSE(10),
	TYPE_DELETE_FILE(11),
	TYPE_APPROVE_BEITRAG(12),
	TYPE_CREATE_CHATRAUM(13),

	// new event types
	DELETE_POST(14),
	CREATE_MENU(15),
	EDIT_MENU(16),
	DELETE_MENU(17);

	final public int id;

	Ereignis(int id) {
		this.id = id;
	}
}
